# dataconnect/connector/queries.gql

query GetAllAppData @auth(level: PUBLIC) {
  students(limit: 100) {
    id
    number
    name
    points
  }
  announcements(limit: 1000) {
    id
    date
    title
    content
    type
  }
  assignments(orderBy: [{ createdAt: DESC }], limit: 1000) {
    id
    dueDate
    title
    subject
    type
    createdAt
    submissions
  }
  dDays(limit: 100) {
    id
    name
    date
  }
  weeklyPlans(limit: 1000) {
    id
    weekKey
    day
    period
    subject
    content
  }
  appConfigs {
    id
    calendarId1
    calendarId2
    calendarId3
    thermometerGoal
    thermometerReward
    dashboardLayouts
  }
  quickLinks(limit: 100) {
    id
    title
    url
    icon
    desc
  }
  polls(limit: 100) {
    id
    question
    options
    votes
  }
  newsletters(limit: 1000) {
    id
    date
    title
    content
    collected
  }
  studentRecords(limit: 3000) {
    id
    student { id }
    type
    content
    category
    date
    createdAt
  }
}

query GetAttendanceByDate($date: Date!) @auth(level: PUBLIC) {
  attendances(where: { date: { eq: $date } }, limit: 100) {
    student { id }
    date
    status
    note
  }
}

query GetAttendanceByMonth($startDate: Date!, $endDate: Date!) @auth(level: PUBLIC) {
  attendances(where: { date: { ge: $startDate, le: $endDate } }, limit: 2000) {
    student { id }
    date
    status
    note
  }
}
